### PR TITLE
Fix/performance

### PR DESCRIPTION
**Pull request by tarikjabiri**
- get rid of string concatenation it is to slow.
- get rid of some unnecessary loops which consume time.

The approach is creating `one array` and push to it all elements and join them at once which is fast.

I replaced `foreach` with `for of` loop but I think there is no performance issue with the foreach also very fast.

This also a fix for the issue #78

### CODE REVIEW

**Comment by thisismhp** [comment]
When will these changes be published?

**Comment by thisismhp** [comment]
When will these changes be released?

**Comment by ognjen-petrovic** [comment]
> 

Done.

**Comment by thisismhp** [comment]
> > 
> 
> Done.

Thank you!

**Pull request merged**
